default_context:
  email: jguibert@gmail.com
  full_name: Jerome Guibert
  github_repo: c4-model
  github_username: geronimo-iia
  max_code_line_length: 120
  package_name: c4_model
  project_name: c4 model
  project_short_description: C4 model utilities
  project_slug: c4-model
  python_major_version: 3
  python_minor_version: 8
  use_coverall: 0
  use_scrutinizer: 0
  year: 2020
_extensions:
  - "jinja2_time.TimeExtension"
